server:
  port: 8081

spring:
  application:
    name: common-service

  redis:
    host: 182.92.106.123
    port: 6379
    password: Lwh750418.
    database: 1
    timeout: 3000
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 20
        max-wait: 20

logging:
  level:
    com.lwh147.common: debug

springfox:
  documentation:
    enabled: true
    packages:
      - com.lwh147
    contact:
      name: lwh147
      url: https://github.com/lwh147