server:
  port: 8081

spring:
  application:
    name: common-service

  redis:
    host: 182.92.106.123
    port: 6379
    password: Lwh750418.
    timeout: 3000

logging:
  level:
    root: info
    com.lwh147.common: debug

swagger:
  enabled: true
  packages:
    - com.lwh147
  contact:
    name: lwh147
    url: https://github.com/lwh147
