server:
  port: 8081

spring:
  application:
    name: common-service

logging:
  level:
    com.lwh147.common: debug

springfox:
  documentation:
    enabled: true
    packages:
      - com.lwh147
    contact:
      name: lwh147
      url: https://github.com/lwh147
